config/routes.rb
Rails.application.routes.draw do
  resources :myposts

end

app/models/mypost.rb
class Mypost < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/myposts_controller.rb
class MypostsController < ApplicationController
  before_action :set_mypost, only: [:show, :edit, :update, :destroy]

  # GET /myposts
  # GET /myposts.json
  def index
    @myposts = Mypost.all
  end

  # GET /myposts/1
  # GET /myposts/1.json
  def show
  end

  # GET /myposts/new
  def new
    @mypost = Mypost.new
  end

  # GET /myposts/1/edit
  def edit
  end

  # POST /myposts
  # POST /myposts.json
  def create
    @mypost = Mypost.new(mypost_params)

    respond_to do |format|
      if @mypost.save
        format.html { redirect_to @mypost, notice: 'Mypost was successfully created.' }
        format.json { render :show, status: :created, location: @mypost }
      else
        format.html { render :new }
        format.json { render json: @mypost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myposts/1
  # PATCH/PUT /myposts/1.json
  def update
    respond_to do |format|
      if @mypost.update(mypost_params)
        format.html { redirect_to @mypost, notice: 'Mypost was successfully updated.' }
        format.json { render :show, status: :ok, location: @mypost }
      else
        format.html { render :edit }
        format.json { render json: @mypost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myposts/1
  # DELETE /myposts/1.json
  def destroy
    @mypost.destroy
    respond_to do |format|
      format.html { redirect_to myposts_url, notice: 'Mypost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mypost
      @mypost = Mypost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mypost_params
      params.require(:mypost).permit(:mytext)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myposts_helper.rb
module MypostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/myposts/_form.html.erb
<%= form_for(@mypost) do |f| %>
  <% if @mypost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mypost.errors.count, "error") %> prohibited this mypost from being saved:</h2>

      <ul>
      <% @mypost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mytext %><br>
    <%= f.text_field :mytext %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myposts/edit.html.erb
<h1>Editing mypost</h1>

<%= render 'form' %>

<%= link_to 'Show', @mypost %> |
<%= link_to 'Back', myposts_path %>

app/views/myposts/index.html.erb
<h1>Listing myposts</h1>

<table>
  <thead>
    <tr>
      <th>Mytext</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @myposts.each do |mypost| %>
      <tr>
        <td><%= mypost.mytext %></td>
        <td><%= link_to 'Show', mypost %></td>
        <td><%= link_to 'Edit', edit_mypost_path(mypost) %></td>
        <td><%= link_to 'Destroy', mypost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mypost', new_mypost_path %>

app/views/myposts/new.html.erb
<h1>New mypost</h1>

<%= render 'form' %>

<%= link_to 'Back', myposts_path %>

app/views/myposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mytext:</strong>
  <%= @mypost.mytext %>
</p>

<%= link_to 'Edit', edit_mypost_path(@mypost) %> |
<%= link_to 'Back', myposts_path %>